FROM openjdk:8-jre-alpine


ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/javalin/chat-websocket-test-1.0-SNAPSHOT.jar"]

#ARG JAR_FILE
ADD build/libs/chat-websocket-test-1.0-SNAPSHOT.jar  /usr/share/javalin/chat-websocket-test-1.0-SNAPSHOT.jar
EXPOSE 7070
