FROM resin/raspberry-pi-openjdk:openjdk-8-jre-20180323


ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/javalin/chat-websocket-test-1.0-SNAPSHOT.jar"]

#ARG JAR_FILE
ADD chat-websocket-test-1.0-SNAPSHOT.jar  /usr/share/javalin/chat-websocket-test-1.0-SNAPSHOT.jar
EXPOSE 7070
